apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec: 
  replicas: 1
  selector:
   matchLabels:
     app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
     containers:
      - name: orders
        image: blazepk/orders
        env: 
          - name : NATS_URL
            value : 'http://nats-srv:4222'
          - name : NATS_CLUSTER_ID
            value : orders
          - name : NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name : MONGO_URI
            value : 'mongodb://orders-mongo-srv:27017/ordersDB'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secrete
                key: JWT_KEY

